output_dir: ~/storage/scratch/experiments/

dataset:
  class: FB15k237LogicalQuery
  path: ~/storage/kg-datasets/sin-anchor/

task:
  class: LogicalQuery
  model:
    class: GNN-QE
    model:
      class: NBFNet
      input_dim: 32
      hidden_dims: [32, 32, 32, 32]
      message_func: distmult
      aggregate_func: pna
      short_cut: yes
      layer_norm: yes
      dependent: yes
    logic: product
    dropout_ratio: 0.25
  criterion: bce
  sample_weight: no
  adversarial_temperature: 0.2

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  gpus: [0]
  batch_size: 12

train:
  num_epoch: 3
  batch_per_epoch: 1000

checkpoint: {{ checkpoint }}
